// <auto-generated />
namespace DDrop.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ReferencePhotoId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReferencePhotoId));
        
        string IMigrationMetadata.Id
        {
            get { return "202010241016025_ReferencePhotoId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
