//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDrop.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDrop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset204 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\lang1033 DDrop\b0\par
        ///
        ///\pard\fi375\qj\f1\fs21\lang1049\&apos;cf\&apos;f0\&apos;ee\&apos;e3\&apos;f0\&apos;e0\&apos;ec\&apos;ec\&apos;e0 DDrop \&apos;f1\&apos;ee\&apos;e7\&apos;e4\&apos;e0\&apos;ed\&apos;e0 \&apos;f1 \&apos;f6\&apos;e5\&apos;eb\&apos;fc\&apos;fe \&apos;ee\&apos;ef\&apos;f2\&apos;e8\&apos;ec\&apos;e8\&apos;e7\&apos;e0\&apos;f6\&apos;e8\&apos;e8 \&apos;ef\&apos;f0\&apos;ee\&apos;f6\&apos;e5\&apos;f1\&apos;f1\&apos;e0 \&apos;ee\&apos;e1\&apos;f0\&apos;e0\ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049{\fonttbl{\f0\fswiss\fprq2\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Calibri;}{\f2\fswiss\fprq2\fcharset204 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\qc\cf1\b\f0\fs33\&apos;d0\&apos;e0\&apos;f1\&apos;f7\&apos;e5\&apos;f2\&apos;ed\&apos;e0\&apos;ff \&apos;ec\&apos;ee\&apos;e4\&apos;e5\&apos;eb\&apos;fc\b0\par
        ///
        ///\pard\widctlpar\fi375\qj\fs21\&apos;d0\&apos;e0\&apos;f1\&apos;f7\&apos;e5\&apos;f2\&apos;ed\&apos;e0\&apos;ff \&apos;ec\&apos;ee\&apos;e4\&apos;e5\&apos;eb\&apos;fc \&apos;e1\&apos;e [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string CalculationModel {
            get {
                return ResourceManager.GetString("CalculationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}{\f3\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;d0\&apos;e0\&apos;e7\&apos;f0\&apos;e0\&apos;e1\&apos;ee\&apos;f2\&apos;f7\&apos;e8\&apos;ea\&apos;e8\b0\f1\lang1033\par
        ///
        ///\pard{\pntext\f3\&apos;B7\tab}{\*\pn\pnlvlblt\pnf3\pnindent0{\pntxtb\&apos;B7}}\fi-360\li720\qj\f0\fs21\lang1049\&apos;cd\&apos;ee\&apos;e2\&apos;e8\&apos;ea\&apos;ee\&apos;e2 \&apos;c2\&apos;eb\&apos;e0\&apos;e4\&apos;e8 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Developers {
            get {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c0\&apos;ea\&apos;ea\&apos;e0\&apos;f3\&apos;ed\&apos;f2\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;c2 \&apos;fd\&apos;f2\&apos;ee\&apos;ec \&apos;ee\&apos;ea\&apos;ed\&apos;e5 \&apos;ee\&apos;f2\&apos;ee\&apos;e1\&apos;f0\&apos;e0\&apos;e6\&apos;e0\&apos;e5\&apos;f2\&apos;f1\&apos;ff \&apos;e8\&apos;ed\&apos;f4\&apos;ee\&apos;f0\&apos;ec\&apos;e0\&apos;f6\&apos;e8\&apos;ff \&apos;ee \&apos;ef\&apos;ee\&apos;eb\&apos;fc\&apos;e7\&apos;ee\&apos;e2\&apos;e0\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceAccount {
            get {
                return ResourceManager.GetString("InterfaceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 00000000000000000000}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0502040204020203}Segoe U [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceAutoCalculation {
            get {
                return ResourceManager.GetString("InterfaceAutoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;d8\&apos;e0\&apos;e1\&apos;eb\&apos;ee\&apos;ed\&apos;fb \&apos;e0\&apos;e2\&apos;f2\&apos;ee\&apos;f0\&apos;e0\&apos;f1\&apos;f7\&apos;e5\&apos;f2\&apos;e0\b0\f1\lang1033\par
        ///
        ///\pard\fi284\qj\f0\fs21\lang1049\&apos;c2 \&apos;f1\&apos;e5\&apos;ea\&apos;f6\&apos;e8\&apos;e8 \&apos;d8\&apos;e0\&apos;e1\&apos;eb\&apos;ee\&apos;ed\&apos;fb \&apos;e0\&apos;e2\&apos;f2\&apos;ee\&apos;f0\&apos;e0\&apos;f1\&apos;f7\&apos;e5\&apos;f2\&apos;e0 \&apos;ec\&apos;ee\&apos;e6\&apos;ed\&apos;e [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceAutoCalculationTemplates {
            get {
                return ResourceManager.GetString("InterfaceAutoCalculationTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f2\fbidi \fmodern\fcharset204\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}
        ///{ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceCommonOptions {
            get {
                return ResourceManager.GetString("InterfaceCommonOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        ///{\f34\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fb [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceCommonSeriesInformation {
            get {
                return ResourceManager.GetString("InterfaceCommonSeriesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0502040204020203}Segoe U [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceInformation {
            get {
                return ResourceManager.GetString("InterfaceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;d3\&apos;f7\&apos;e5\&apos;f2\&apos;ed\&apos;fb\&apos;e5 \&apos;e7\&apos;e0\&apos;ef\&apos;e8\&apos;f1\&apos;e8\b0\f1\lang1033\par
        ///
        ///\pard\fi284\qj\f0\fs21\lang1049\&apos;c2 \&apos;f1\&apos;e5\&apos;ea\&apos;f6\&apos;e8\&apos;e8 \&apos;d3\&apos;f7\&apos;e5\&apos;f2\&apos;ed\&apos;fb\&apos;e5 \&apos;e7\&apos;e0\&apos;ef\&apos;e8\&apos;f1\&apos;e8 \&apos;ec\&apos;ee\&apos;e6\&apos;ed\&apos;ee \&apos;f3\&apos;e4\&apos;e0\&apos;eb\&apos;ff\&apos;f2\&apos;fc \&apos;eb\&apos;ee\ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceLocalStoredUsers {
            get {
                return ResourceManager.GetString("InterfaceLocalStoredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f34\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fbidi \fswiss\fcharset204\fprq2{\*\panose 00000000000000000000}Segoe UI;}
        ///{ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceManualEdit {
            get {
                return ResourceManager.GetString("InterfaceManualEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f34\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0502040204020203}Segoe UI;}
        ///{ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceManualThermalEdit {
            get {
                return ResourceManager.GetString("InterfaceManualThermalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        ///{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceMenu {
            get {
                return ResourceManager.GetString("InterfaceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f34\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fbidi \fswiss\fcharset204\fprq2{\*\panose 00000000000000000000}Segoe UI;}
        ///{ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfacePlot {
            get {
                return ResourceManager.GetString("InterfacePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0502040204020203}Segoe U [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceReOrdering {
            get {
                return ResourceManager.GetString("InterfaceReOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f34\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fbidi \fswiss\fcharset204\fprq2{\*\panose 00000000000000000000}Segoe UI;}
        ///{ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InterfaceSeriesManager {
            get {
                return ResourceManager.GetString("InterfaceSeriesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c4\&apos;ee\&apos;e1\&apos;e0\&apos;e2\&apos;eb\&apos;e5\&apos;ed\&apos;e8\&apos;e5\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;d7\&apos;f2\&apos;ee\&apos;e1\&apos;fb \&apos;e4\&apos;ee\&apos;e1\&apos;e0\&apos;e2\&apos;e8\&apos;f2\&apos;fc \&apos;ed\&apos;ee\&apos;e2\&apos;f3\&apos;fe \&apos;f1\&apos;e5\&apos;f0\&apos;e8\&apos;fe \&apos;ed\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;ee:\par
        ///
        ///\pard 
        ///{\p [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsAddSeries {
            get {
                return ResourceManager.GetString("OperationsAddSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c4\&apos;ee\&apos;e1\&apos;e0\&apos;e2\&apos;eb\&apos;e5\&apos;ed\&apos;e8\&apos;e5 \&apos;f8\&apos;e0\&apos;e1\&apos;eb\&apos;ee\&apos;ed\&apos;e0\b0\f1\lang1033\par
        ///
        ///\pard\qj\f0\fs21\lang1049\&apos;cf\&apos;ee\&apos;eb\&apos;fc\&apos;e7\&apos;ee\&apos;e2\&apos;e0\&apos;f2\&apos;e5\&apos;eb\&apos;fc \&apos;ec\&apos;ee\&apos;e6\&apos;e5\&apos;f2 \&apos;e4\&apos;ee\&apos;e1\&apos;e0\&apos;e2\&apos;e8\&apos;f2\&apos;fc \&apos;ed\&apos;ee\&apos;e2\&apos;fb\&apos;e9 \&apos;f8\&apos;e0\ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsAutoCalcAddTemplate {
            get {
                return ResourceManager.GetString("OperationsAutoCalcAddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;cd\&apos;e0\&apos;f1\&apos;f2\&apos;f0\&apos;ee\&apos;e9\&apos;ea\&apos;e0 \f1\lang1033 Python \f0\lang1049\&apos;ee\&apos;e1\&apos;f0\&apos;e0\&apos;e1\&apos;ee\&apos;f2\&apos;f7\&apos;e8\&apos;ea\&apos;e0\b0\f1\lang1033\par
        ///
        ///\pard\qj\f0\fs21\lang1049\&apos;d0\&apos;e0\&apos;e1\&apos;ee\&apos;f2\&apos;e0 \&apos;f1 \f1\lang1033 Python \f0\lang1049\&apos;ee\&apos;e1\&apos;f0\&apos;e0\&apos;e1\&apos;ee\&apos;f [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsAutoCalcPython {
            get {
                return ResourceManager.GetString("OperationsAutoCalcPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset204 Calibri;}{\f3\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;ce\&apos;e1\&apos;f9\&apos;e5\&apos;e5\b0\f1\lang1033\par
        ///
        ///\pard\qj\f0\fs21\lang1049\&apos;d7\&apos;f2\&apos;ee\&apos;e1\&apos;fb \&apos;ed\&apos;e0\&apos;f7\&apos;e0\&apos;f2\&apos;fc \&apos;e0\&apos;e2\&apos;f2\&apos;ee\&apos;ec\&apos;e0\&apos;f2\&apos;e8\&apos;f7\&apos;e5\&apos;f1\&apos;ea\&apos;e8\&apos;e9 \&apos;f0\&apos;e0\&apos;f1\&apos;f7\&apos;e5\&apos;f2 \&apos;ed\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;e [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsAutoCalculationCommon {
            get {
                return ResourceManager.GetString("OperationsAutoCalculationCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;d8\&apos;e0\&apos;e1\&apos;eb\&apos;ee\&apos;ed\&apos;fb \&apos;e0\&apos;e2\&apos;f2\&apos;ee\&apos;f0\&apos;e0\&apos;f1\&apos;f7\&apos;e5\&apos;f2\&apos;e0\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;d8\&apos;e0\&apos;e1\&apos;eb\&apos;ee\&apos;ed\&apos;fb \&apos;e0\&apos;e2\&apos;f2\&apos;ee\&apos;f0\&apos;e0\&apos;f1\&apos;f7\&apos;e5\&apos;f2\&apos;e0 \&apos;ef\&apos;ee\&apos;e7\&apos;e2\&apos;ee\&apos;eb\&apos;ff\&apos;fe\&apos;f2 \&apos;f1\&apos;ee\&apos;f5 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsAutoCalculationTemplatesOp {
            get {
                return ResourceManager.GetString("OperationsAutoCalculationTemplatesOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c0\&apos;e2\&apos;f2\&apos;ee\&apos;ec\&apos;e0\&apos;f2\&apos;e8\&apos;f7\&apos;e5\&apos;f1\&apos;ea\&apos;e8\&apos;e9 \f1\lang1033 Excel \f0\lang1049\&apos;ee\&apos;f2\&apos;f7\&apos;e5\&apos;f2\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;d1\&apos;e5\&apos;f0\&apos;e8\&apos;e8, \&apos;e4\&apos;eb\&apos;ff \&apos;ea\&apos;ee\&apos;f2\&apos;ee\&apos;f0\&apos;fb\&apos;f5 \&apos;e2\&apos;ee\&apos;e7\&apos;ec\&apos;ee\&apos;e6 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsAutoExcelReport {
            get {
                return ResourceManager.GetString("OperationsAutoExcelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f43\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0502040204020203}Segoe U [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsCommonOperations {
            get {
                return ResourceManager.GetString("OperationsCommonOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;ce\&apos;e1\&apos;f9\&apos;e8\&apos;e9 \&apos;ed\&apos;e0\&apos;f1\&apos;f2\&apos;f0\&apos;ee\&apos;e9\&apos;ea\&apos;e8\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;dd\&apos;f2\&apos;e0 \&apos;f1\&apos;e5\&apos;ea\&apos;f6\&apos;e8\&apos;ff \&apos;ee\&apos;ef\&apos;f6\&apos;e8\&apos;e9 \&apos;f1\&apos;ee\&apos;f1\&apos;f2\&apos;ee\&apos;e8\&apos;f2 \&apos;e8\&apos;e7 \&apos;e4\&apos;e2\&apos;f3\&apos;f5 \&apos;ef\&apos;f3\&apos;ed\&apos;ea\&apos;f2\&apos;ee\ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsCommonOptionsOp {
            get {
                return ResourceManager.GetString("OperationsCommonOptionsOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c8\&apos;ec\&apos;ef\&apos;ee\&apos;f0\&apos;f2 \&apos;e8 \&apos;fd\&apos;ea\&apos;f1\&apos;ef\&apos;ee\&apos;f0\&apos;f2\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;d1\&apos;e5\&apos;f0\&apos;e8\&apos;e8 \&apos;ec\&apos;ee\&apos;e6\&apos;ed\&apos;ee \&apos;fd\&apos;ea\&apos;f1\&apos;ef\&apos;ee\&apos;f0\&apos;f2\&apos;e8\&apos;f0\&apos;ee\&apos;e2\&apos;e0\&apos;f2\&apos;fc \&apos;e8 \&apos;e8\&apos;ec\&apos;ef\&apos;ee\&apos;f0\&apos;f2\&apos;e8\&apos;f0\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsImportExport {
            get {
                return ResourceManager.GetString("OperationsImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;cb\&apos;ee\&apos;ea\&apos;e0\&apos;eb\&apos;fc\&apos;ed\&apos;fb\&apos;e5 \&apos;f3\&apos;f7\&apos;e5\&apos;f2\&apos;ed\&apos;fb\&apos;e5 \&apos;e7\&apos;e0\&apos;ef\&apos;e8\&apos;f1\&apos;e8\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;cf\&apos;f0\&apos;e8 \&apos;f3\&apos;f1\&apos;ef\&apos;e5\&apos;f8\&apos;ed\&apos;ee\&apos;e9 \&apos;e0\&apos;e2\&apos;f2\&apos;ee\&apos;f0\&apos;e8\&apos;e7\&apos;e0\&apos;f6\&apos;e8\&apos;e8 \&apos;f1 \&apos;ee\&apos;f2\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsLocalStoredUsersOp {
            get {
                return ResourceManager.GetString("OperationsLocalStoredUsersOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c4\&apos;ee\&apos;e1\&apos;e0\&apos;e2\&apos;eb\&apos;e5\&apos;ed\&apos;e8\&apos;e5\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;d7\&apos;f2\&apos;ee\&apos;e1\&apos;fb \&apos;e7\&apos;e0\&apos;e3\&apos;f0\&apos;f3\&apos;e7\&apos;e8\&apos;f2\&apos;fc \&apos;ed\&apos;ee\&apos;e2\&apos;fb\&apos;e5 \&apos;f4\&apos;ee\&apos;f2\&apos;ee\&apos;e3\&apos;f0\&apos;e0\&apos;f4\&apos;e8\&apos;e8 \&apos;ed\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsPhotosAdd {
            get {
                return ResourceManager.GetString("OperationsPhotosAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;d0\&apos;f3\&apos;f7\&apos;ed\&apos;ee\&apos;e5 \&apos;f0\&apos;e5\&apos;e4\&apos;e0\&apos;ea\&apos;f2\&apos;e8\&apos;f0\&apos;ee\&apos;e2\&apos;e0\&apos;ed\&apos;e8\&apos;e5\b0\f1\lang1033\par
        ///
        ///\pard\fi375\sl240\slmult1\qj\f0\fs21\lang1049\&apos;cf\&apos;f0\&apos;e8 \&apos;ed\&apos;e0\&apos;e6\&apos;e0\&apos;f2\&apos;e8\&apos;e8 \&apos;ed\&apos;e0 \&apos;ea\&apos;ed\&apos;ee\&apos;ef\&apos;ea\&apos;f3 \&apos;e2 \&apos;f4\&apos;ee\&apos;f0\&apos;ec\&apos;e5 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsPhotosEdit {
            get {
                return ResourceManager.GetString("OperationsPhotosEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;cf\&apos;e5\&apos;f0\&apos;e5\&apos;f0\&apos;e0\&apos;f1\&apos;f7\&apos;e5\&apos;f2\b0\f1\lang1033\par
        ///
        ///\pard\fi375\sa200\sl276\slmult1\qj\f0\fs21\lang1049\&apos;ca\&apos;ed\&apos;ee\&apos;ef\&apos;ea\&apos;e0 &quot;\&apos;cf\&apos;e5\&apos;f0\&apos;e5\&apos;f1\&apos;f7\&apos;e8\&apos;f2\&apos;e0\&apos;f2\&apos;fc \&apos;ef\&apos;e0\&apos;f0\&apos;e0\&apos;ec\&apos;e5\&apos;f2\&apos;f0\&apos;fb \&apos;ea\&apos;e0\&apos;ef\&apos;e5\&apos;eb\&apos;fc&quot; {\ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsPhotosReCalculate {
            get {
                return ResourceManager.GetString("OperationsPhotosReCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c8\&apos;e7\&apos;ec\&apos;e5\&apos;ed\&apos;e5\&apos;ed\&apos;e8 \&apos;ef\&apos;ee\&apos;f0\&apos;ff\&apos;e4\&apos;ea\&apos;e0\b0\f1\lang1033\par
        ///
        ///\pard\fi375\sa200\sl276\slmult1\qj\f0\fs21\lang1049\&apos;c4\&apos;eb\&apos;ff \&apos;ef\&apos;e5\&apos;f0\&apos;e5\&apos;f5\&apos;ee\&apos;e4\&apos;e0 \&apos;e2 \&apos;f0\&apos;e5\&apos;e6\&apos;e8\&apos;ec \&apos;e8\&apos;e7\&apos;ec\&apos;e5\&apos;ed\&apos;e5\&apos;ed\&apos;e8\&apos;ff \&apos;ef\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsPhotosReOrder {
            get {
                return ResourceManager.GetString("OperationsPhotosReOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c3\&apos;f0\&apos;e0\&apos;f4\&apos;e8\&apos;ea\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;cf\&apos;f0\&apos;e8 \&apos;f1\&apos;ee\&apos;e7\&apos;e4\&apos;e0\&apos;ed\&apos;e8\&apos;e8 \&apos;ed\&apos;ee\&apos;e2\&apos;ee\&apos;e9 \&apos;f1\&apos;e5\&apos;f0\&apos;e8\&apos;e8 \&apos;ea\&apos;ed\&apos;ee\&apos;ef\&apos;ea\&apos;e0 \&apos;e3\&apos;f0\&apos;e0\&apos;f4\&apos;e8\&apos;ea \&apos;ed\&apos;e5\&apos;e4\&apos;ee\&apos;f1\&apos;f2\&apos;f3\&apos;ef\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsPlot {
            get {
                return ResourceManager.GetString("OperationsPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;ce\&apos;e1\&apos;f9\&apos;e8\&apos;e9 \&apos;e3\&apos;f0\&apos;e0\&apos;f4\&apos;e8\&apos;ea \&apos;f1\&apos;e5\&apos;f0\&apos;e8\&apos;e9\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;d7\&apos;f2\&apos;ee\&apos;e1\&apos;fb \&apos;ef\&apos;ee\&apos;f1\&apos;f2\&apos;f0\&apos;ee\&apos;e8\&apos;f2\&apos;fc\f1\lang1033  \f0\lang1049\&apos;ee\&apos;e1\&apos;f9\&apos;e8\&apos;e9 \&apos;e3\&apos;f0\&apos;e0\&apos;f4\&apos;e8\&apos;ea \ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsPlotOperations {
            get {
                return ResourceManager.GetString("OperationsPlotOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;c4\&apos;ee\&apos;e1\&apos;e0\&apos;e2\&apos;eb\&apos;e5\&apos;ed\&apos;e8\&apos;e5\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;d7\&apos;f2\&apos;ee\&apos;e1\&apos;fb \&apos;e4\&apos;ee\&apos;e1\&apos;e0\&apos;e2\&apos;e8\&apos;f2\&apos;fc \&apos;ed\&apos;ee\&apos;e2\&apos;fb\&apos;e9 \&apos;f0\&apos;e5\&apos;f4\&apos;e5\&apos;f0\&apos;e5\&apos;ed\&apos;f1\&apos;ed\&apos;fb\&apos;e9 \&apos;f1\&apos;ed\&apos;e8\&apos;ec\&apos;ee\&apos;ea, \&apos;ed\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;e [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsReferenceAdd {
            get {
                return ResourceManager.GetString("OperationsReferenceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;d0\&apos;e5\&apos;e4\&apos;e0\&apos;ea\&apos;f2\&apos;e8\&apos;f0\&apos;ee\&apos;e2\&apos;e0\&apos;ed\&apos;e8\&apos;e5\b0\f1\lang1033\par
        ///
        ///\pard\fi375\qj\f0\fs21\lang1049\&apos;cf\&apos;ee\&apos;f1\&apos;eb\&apos;e5 \&apos;e2\&apos;fb\&apos;e1\&apos;ee\&apos;f0\&apos;e0 \&apos;f0\&apos;e5\&apos;f4\&apos;e5\&apos;f0\&apos;e5\&apos;ed\&apos;f1\&apos;e0, \&apos;f4\&apos;ee\&apos;f2\&apos;ee\&apos;e3\&apos;f0\&apos;e0\&apos;f4\&apos;e8\&apos;ff \&apos;ee\&apos;f2\&apos;ee\&apos;e [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OperationsReferenceEdit {
            get {
                return ResourceManager.GetString("OperationsReferenceEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset204 Segoe UI;}{\f1\fnil\fcharset0 Segoe UI;}{\f2\fnil\fcharset0 Calibri;}{\f3\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\qc\cf1\b\f0\fs33\&apos;d2\&apos;e5\&apos;f1\&apos;f2\&apos;e8\&apos;f0\&apos;ee\&apos;e2\&apos;f9\&apos;e8\&apos;ea\&apos;e8\b0\f1\lang1033\par
        ///
        ///\pard{\pntext\f3\&apos;B7\tab}{\*\pn\pnlvlblt\pnf3\pnindent0{\pntxtb\&apos;B7}}\fi-360\li720\qj\f0\fs21\lang1049\&apos;c0\&apos;ed\&apos;e4\&apos;f0\&apos;e5\&apos;e9 \&apos;cb\&apos;e8\&apos;f2\&apos;f3\&apos;ed\&apos;ee [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Testers {
            get {
                return ResourceManager.GetString("Testers", resourceCulture);
            }
        }
    }
}
